#spring:
#  datasource:
#    url: jdbc:h2:file:~/minervinidb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  devtools:
#    restart:
#      enabled: true
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.xml
#jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#  show-sql: true
#  hibernate:
#    ddl-auto: validate
#h2:
#  console:
#    enabled: true
#    path: /h2-console
#sql:
#  init:
#    platform: h2

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Minervini
    username: postgres
    password: 123456
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 3000000
  security:
    user:
      name: admin
      password: demo@123

# Spring security
#  jwtCookieName: minerviniCookie
#  jwtSecret: 123xxx123
#  jwtExpirationMs: 86400000
#logging:
#  level:
#    org:
#      springframework:
#        beans:
#          factory: DEBUG
